default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '') %>
  password: <%= ENV.fetch('DB_PASS', '') %>
  username: <%= ENV.fetch('DB_USER', '') %>
development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'github_search_dev') %>
test:
  <<: *default
  database: job_market_place_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'github_search') %>
