# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  github:
    client_id: ''
    client_secret: ''
  secret_key_base: 6b0eb993beb628dd35c84f6cc4491ba7881c767f657f377a1899dad2cfba81c8ee793464be078013b2cdf649a48b5fd0adb80c78851149e1590235cb5bc12932

test:
  secret_key_base: 29f2ce167bdbd8d40ccb003f94049a9c53d6a6a589c0994599d5f6f416291ecefebb43fb19e4978132831f666198575535d509410f45c8ed6eb4a267d6f6af1d
  github:
    client_id: ''
    client_secret: ''
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github:
    client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
    client_secret: <%= ENV["GITHUB_SECRET"]%>
